### ISSUE TITLE
Doesn't decrypt what was encrypted

### ISSUE THREAD

**Issue by fakewaffle** [zacbarton/node-cf-encrypt#1]
cf-encrypt.js:

``` javascript
'use strict';

var assert  = require( 'assert' );
var encrypt = require( 'cf-encrypt' );

var encrypted = encrypt.encrypt( 'my-key', 'testfoo', 'hex' );
var decrypted = encrypt.decrypt( 'my-key', encrypted, 'hex' );

assert.equal( 'testfoo', decrypted );
```

Bash:

``` bash
~/Source/temp
> node cf-encrypt.js

assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "testfoo" == "test��-"
    at Object.<anonymous> (~/Source/temp/cf-encrypt.js:9:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by zacbarton** [comment]
@fakewaffle what platform are you on because running the above doesn't throw an error for me.

**Comment by fakewaffle** [comment]
OS X Yosemite 10.10.2. Node.js v0.10.35

**Comment by mashu-daishi** [comment]
I'm seeing the same issue with the same OS. Any progress?

**Comment by fakewaffle** [comment]
Works! Thanks a lot! :smile:

**Comment by zacbarton** [comment]
No worries @fakewaffle
